### ISSUE TITLE
Refetch does not trigger subscribe

### ISSUE THREAD

**Issue by conor-mac-aoidh** [apollographql/apollo-angular#176] opened 2016-12-02 12:37 UTC
This is a question/possible bug about the `refetch` method documented [here](http://dev.apollodata.com/angular2/receiving-updates.html#Refetches).

I noticed that `refetch` returns a promise that resolves the new data. However, I had expected that a subscription on the original query would be triggered when `refetch` is called. This is not the case, eg:

```ts
ngOnInit() {
  this.query = this.apollo.watchQuery({query: TestQuery});
  this.query.subscribe(({data}) => {
    console.log(data);
  });
}

refetch() {
  this.query.refetch();
}
```

I would expect the subscribe callback to be triggered again after `refetch` is executed. Could someone clarify why this does not happen?

Thanks

**Comment by kamilkisiela** [comment] 2016-12-14 18:49
Could you create a repository with reproduction? It would be much easier to me to test it :)

**Comment by kamilkisiela** [comment] 2016-12-15 14:43
I've made [a reproduction](https://github.com/kamilkisiela/angular2-apollo-reproduction/tree/176). It works for me. Could you play with it to show the issue?

**Comment by conor-mac-aoidh** [comment] 2016-12-15 17:34
@kamilkisiela Thanks for creating. The issue indeed does not occur in the repository you created. However, it does occur in my app.. I'm not sure what differences are (frontend code is very similar)..

But I am using a different backend - [absinthe](https://github.com/absinthe-graphql/absinthe)

I will take another look at this tomorrow, and see if I can diagnose any further the cause of the issue. Thanks.

**Comment by kamilkisiela** [comment] 2016-12-16 12:13
@conor-mac-aoidh It not suppose to be related to a backend so there should be something different in our codes. Maybe some package has different version etc?

**Comment by conor-mac-aoidh** [comment] 2016-12-16 15:32
@kamilkisiela I'm not sure.. I have updated to the same angular2-apollo, apollo-client, angular, rxjs modules that are used in your reproduction app but no change.. I can't find what is causing this, maybe it is something about my app setup (based on angular-cli generated app)

**Comment by kamilkisiela** [comment] 2017-01-03 06:42
@conor-mac-aoidh Any progress?

**Comment by kamilkisiela** [comment] 2017-01-26 13:58
Closing this for now

**Comment by Ramzeus** [comment] 2017-04-19 12:59
I seem to have the same problem

**Comment by Eraldo** [comment] 2017-11-28 23:59
I also have the same problem.
How about reopening the issue?

**Comment by blissi** [comment] 2018-03-30 08:03
I'm also having this issue.
To narrow it down and to play around with it, I then simulated an error on every 3rd invocation in the backend - in case of the error the subscription is called! Just not in case of a successful backend call.

The query is created like this:
```
this.query = this.apollo.watchQuery({
				query: GetShippingsList,
				errorPolicy: "all"
			});
```

**Comment by kamilkisiela** [comment] 2018-03-30 08:05
If guys could prepare a reproduction of this then it would be easier to fix it.

**Comment by blissi** [comment] 2018-03-30 10:32
@kamilkisiela  I debugged it and I think I found the issue - it's in Apollo Client and not in Apollo Angular.
I created a bug over there:
https://github.com/apollographql/apollo-client/issues/3235

**Comment by kamilkisiela** [comment] 2018-03-30 10:35
That might be true, Apollo Angular itself isn't involved in any of ApolloClient internals, it's just a wrapper to make things more convenient to use in Angular apps. 

I think we can close this one now.

**Comment by kamilkisiela** [comment] 2018-03-30 10:35
@blissi Thank you :))

**Closed by kamilkisiela** 2018-03-30 10:35 UTC
