### ISSUE TITLE
apollo-angular doesn't work with Angular Universal using ts-node

### ISSUE THREAD

**Issue by ravishivt** [apollographql/apollo-angular#585] opened 2018-04-25 01:04 UTC
apollo-angular contains `import` and `export` statements in the published npm package (v1.0.1).  These `import`/`export` statements break Angular Universal when starting the server with ts-node.

`SyntaxError: Unexpected token import`

**Comment by ravishivt** [comment] 2018-04-25 01:37
Submitted a PR.  The problem was `module: es2015` in tsconfig.json.   No value should be specified so it defaults to `CommonJS` which transpiles `import` to `require`.  https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by kamilkisiela** [comment] 2018-04-25 05:27
We have a UMD bundle with es5 + commonjs, other files are in es5 too but with import / export. It should work and it does work. Maybe you import something nested, like `import {} from 'apollo-angular/Apollo'` which will use a file with import export statements.

**Comment by kamilkisiela** [comment] 2018-04-25 06:17
As you can see here:

Bundle file - https://unpkg.com/apollo-angular@1.0.1
ES6 Modules - https://unpkg.com/apollo-angular@1.0.1/

And the [`package.json`](https://unpkg.com/apollo-angular@1.0.1/package.json) that contains:

```
main: "bundle.umd.js",
module: "index.js",
jsnext:main: "index.js",
```

main - is for browsers
module - points to an entry point with es modules
jsnext:main - does the same as module

**Comment by ravishivt** [comment] 2018-04-25 23:56
I found out why it wasn't working.  I was using ts-node to compile and run my Angular Universal server.ts but ts-node doesn't [compile files in node_modules](https://github.com/TypeStrong/ts-node/issues/505).

I suppose this isn't `apollo-angular`'s fault, but it is annoying since it is the only third-party module my project uses that packages their files in this way.  Also as an fyi, ts-node is being recommended by some Angular Universal tutorials such as https://blog.angular-university.io/angular-universal/.

**Comment by kamilkisiela** [comment] 2018-04-26 07:12
Could you create a simple reproduction?

**Comment by ravishivt** [comment] 2018-04-26 19:12
Sure, https://github.com/ravishivt/apollo-angular-ssr/tree/pr1.

It's a fork of your https://github.com/kamilkisiela/apollo-angular-ssr.  I merged the fixes in https://github.com/kamilkisiela/apollo-angular-ssr/pull/1.  The only other thing changed was installing `ts-node` and using that to compile and run `server.ts` instead of using webpack. 

Once cloned, run:

```
$ npm install
$ npm run build:client-and-server-bundles
$ ./node_modules/ts-node/dist/bin.js server.ts
(...)/apollo-angular-ssr/node_modules/apollo-angular/Apollo.js:19
import { Injectable } from '@angular/core';
^^^^^^

SyntaxError: Unexpected token import
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (internal/modules/cjs/loader.js:618:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
```

**Comment by kamilkisiela** [comment] 2018-05-13 12:47
@ravishivt Try to attach a `yarn.lock` or `package-lock.json` or just remove them and install packages again because right now, it doesn't work for me, dependencies are missing, they are in wrong versions.

**Comment by kamilkisiela** [comment] 2018-05-18 11:13
What you proposed, using commonjs modules, is not a real solution of a problem. It will fix it, of course, but files like `apollo-angular/Apollo` are meant to use `import / export` statements. That's why `"module"` exists in `package.json`.

`ts-node` shouldn't compile any code from `node_modules` and you see that error because it tries to compile one of those files (`apollo-angular/Apollo.js`). That means that either configuration is wrong or the way `dist/server/main.bundle.js` is being used.

**Comment by bojidaryovchev** [comment] 2018-05-29 20:55
I had this problem so what I did was to clone the apollo-angular repository and build the apollo-angular and apollo-angular-link-http packages as commonjs modules.. Then I replaced the files and everything worked fine

**Comment by nicky-lenaers** [comment] 2018-06-19 10:12
After I found out I was using `webpack-node-externals`, I solved this by using the following in my `webpack.config.ts` file:

```ts
externals: [
  WebpackNodeExternals({
    whitelist: [
      /apollo-angular/,
      /@angular\/common\/locales/
    ]
  })
],
```

Hope it helps!

**Comment by jonasarcangel** [comment] 2018-08-09 21:54
I'm getting a similar issue, but with the "{" token.

[https://stackoverflow.com/questions/51774716/apollomodule-js-syntaxerror-unexpected-token](https://stackoverflow.com/questions/51774716/apollomodule-js-syntaxerror-unexpected-token)

**Comment by kamilkisiela** [comment] 2018-08-21 17:38
@nicky-lenaers @bojidaryovchev @ravishivt 
Could you check v1.2.0? We switched to use `ng-packagr` so it nows contains flat modules etc.

**Comment by kamilkisiela** [comment] 2018-08-28 10:36
I guess I can close it
https://github.com/kamilkisiela/apollo-angular-ssr/tree/ts-node

**Closed by kamilkisiela** 2018-08-28 10:36 UTC
