### ISSUE TITLE
string query variable unexpectedly expanded to char variables additionally

### ISSUE THREAD

**Issue by Eraldo** [apollographql/apollo-angular#449] opened 2017-12-11 02:28 UTC
I have a query watch call that I call like this:
```ts
   this.query$ = this.apollo.watchQuery({
      query: Query,
      variables: {date: "2017-12-11"}
    });
    this.query$.valueChanges.subscribe(...)
```

And the request payload then looks like this:
```
{operationName: "Query",…}
operationName: "Query"
query: "query Query($date: String!) {↵  viewer {↵    id↵    scans(date: $date) {↵      edges {↵        node {↵          id↵          date↵          area1↵          area2↵          area3↵          area4↵          area5↵          area6↵          area7↵          __typename↵        }↵        __typename↵      }↵      __typename↵    }↵    __typename↵  }↵}↵"
variables: {0: "2", 1: "0", 2: "1", 3: "7", 4: "-", 5: "1", 6: "2", 7: "-", 8: "1", 9: "1", date: "2017-12-11"}
```
The last line looks broken to me!
I would expect `variables: {date: "2017-12-11"}` but instead every character is also sent as a variable!?
That was not the case before I upgraded to version 2.

More info on my setup: https://github.com/apollographql/apollo-client/issues/2706#issuecomment-350602437

**Comment by kamilkisiela** [comment] 2017-12-13 15:27
Could you try to reproduce it?
https://stackblitz.com/edit/simple-apollo-angular-example

**Comment by Eraldo** [comment] 2017-12-16 20:07
I tried.. but I could not reproduce it. :/
I did get the expected variables in that stackblitz environment.

So I guess it is safe to conclude that it is not a general issue but depends on some environment thing that I don't yet know.
Further ideas?

**Comment by Eraldo** [comment] 2017-12-16 20:08
Thank's for the idea of using that service to find that out. ;)

**Comment by kamilkisiela** [comment] 2018-01-27 20:08
Closing since I didn't receive any reproduction

**Closed by kamilkisiela** 2018-01-27 20:08 UTC
