### ISSUE TITLE
SSR: authorization header isn't added

### ISSUE THREAD

**Issue by okkevdeijk** [apollographql/apollo-angular#765] opened 2018-08-21 14:08 UTC
Hi there,

First of all: the apollo-angular library has been very great work, big thanks. Its' working excellent for everything related to GraphQL and Angular. However, I'm running into issues when I'm trying to use Server Side Rendering (Angular Universal).  I'm using an GraphQL endpoint that does require an Authorization token. On client-side the authentication client is working great,  however when I disable javascript I get a 401 unauthorized message from the GraphQL service I am using.

I followed the [Server Side Rendering tutorial](https://www.apollographql.com/docs/angular/recipes/server-side-rendering.html#server-rendering), which explains that nothing else is required:

> You can render your entire Angular-based Apollo application on a Node server the same way as you would normally do with an Angular app. No changes are required to client queries to support this, so your Apollo-based Angular UI should support SSR out of the box.

I am using the following code:

```
 public graphQLClient() {
      // using a situation with an anonymous and authenticatad token
        const anonymousToken = this.getAnonymousAccesToken();
        const authenticatedToken = this.getAuthenticatedToken();
        if (anonymousToken) {
            this.createAuthMiddlewareGraphQL(anonymousToken);
        }
        if (authenticatedToken) {
            this.createAuthMiddlewareGraphQL(authenticatedToken);
        }
        if (!anonymousToken && !authenticatedToken) {
            // create an anonymoous token
            this.createAnonymousclient()
                .then(() => {
                    this.graphQLClient();
                })
                .catch(err => {
                });
        }

    }

```

```
    public createAuthMiddlewareGraphQL(token: string) {
        const http = this.httpLink.create({
            uri: environment + '/' + 'graphql',
        });

        const authMiddleware = new ApolloLink((operation, forward) => {

            operation.setContext({
                headers: new HttpHeaders().set('Authorization', `Bearer ${token}`)
            });

            return forward(operation);
        });

        this.apollo.create({
            link: authMiddleware.concat(http),
            cache: new InMemoryCache()
        });
    }
```

Error:
```
ERROR { Error: Network error: Http failure response for ***************: 401 Unauthorized
    at new ApolloError (.....\dist\server.js:323584:28))
  graphQLErrors: [],
  networkError:
   HttpErrorResponse {
     headers:
      HttpHeaders {
        normalizedNames: Map {},
        lazyUpdate: null,
        lazyInit: [Function] },
     status: 401,
     statusText: 'Unauthorized',
     url: '*******',
     ok: false,
     name: 'HttpErrorResponse',
     message:
      'Http failure response for **********: 401 Unauthorized',
     error:
      { statusCode: 401,
        message:
         '****************.',
        errors: [Array],
        error: 'access_denied',
        error_description:
         'This endpoint requires an access token. You can get one from the authorization server.' } },
  message:
   'Network error: Http failure response for ************: 401 Unauthorized',
  extraInfo: undefined }

```

It looks like on server side the authorzation header isn't set. What am I doing wrong? Do I need to await the operation response? Thanks in advance!

**Comment by Lotafak** [comment] 2018-08-24 10:50
I think I have similar issue (Also similar code)

```
export class AppModule {
  constructor(
    apollo: Apollo,
    httpLink: HttpLink,
  ) {
    const http = httpLink.create({ uri: environment.graphqlServer });

    const authMiddleware = new ApolloLink((operation, forward) => {
      const jwt = localStorage.getItem('token');
      operation.setContext({
        headers: jwt !== null ? new HttpHeaders().set('Authorization', `Bearer ${jwt}`) : '',
      });

      return forward(operation);
    });
}
```

I debugged the wrong request and it appears that `jwt` variable is actually correctly set. The response from the server tho is unauthorized because `Authorization` header is not set in the request. If you need more information I'll be happy to provide them

**Comment by kamilkisiela** [comment] 2018-08-28 10:37
Could you create a reproduction based on this repository?

https://github.com/kamilkisiela/apollo-angular-ssr

**Comment by kamilkisiela** [comment] 2018-09-16 08:53
@Lotafak 

> The behaviour of this request is correct the second time I'm invoking the method which makes a request. The workaround then would be to call the method twice if the first one didn't succeed, and it actually works, but it seems dirty.

What to you mean by invoking the method for the second time? The next query that runs gets it correctly?

**Comment by kamilkisiela** [comment] 2018-10-16 16:38
Closing since I didn't receive any reproduction yet. @mention me if there's one.

**Closed by kamilkisiela** 2018-10-16 16:38 UTC
Labels: bug, help wanted
