### ISSUE TITLE
ApolloQueryObservable.map does not exist

### ISSUE THREAD

**Issue by davideberlein** [apollographql/apollo-angular#322] opened 2017-06-23 14:28 UTC
When creating a new project with the angular cli and importing ApolloQueryObservable. The map function is somehow not available:
``` typescript
this.users = this.apollo.watchQuery<UsersQuery>({
            query: UsersQueryNode,
            variables: {
              id: data.users,
            },
          }).map(result => result.data.users) as any;
```

The TS compiler says:

 > Property 'map' does not exist on type 'ApolloQueryObservable<UsersQuery>'.

My dependcies:
```json
 "dependencies": {
    "@angular/animations": "^4.0.0",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@types/node": "^6.0.78",
    "apollo-angular": "^0.13.0",
    "apollo-client": "^1.5.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.1.2",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/language-service": "^4.0.0",
    "@types/jasmine": "2.5.45",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
```

**Comment by dotansimha** [comment] 2017-06-24 08:13
Duplicate of: https://github.com/apollographql/apollo-angular/issues/308

**Closed** 2017-06-26 07:14 UTC

**Comment by Urigo** [comment] 2017-06-26 10:25
@eitanfr might be worth adding an explicit sentence to add it in the docs as this is the second time people are confused with it

**Comment by davideberlein** [comment] 2017-06-26 10:44
The solution of the duplicate worked for me, however adding additional methods to an already imported type via an extra import is rather unusual (for me as TypeScript newbe at least) so a hint in the doc would have helped.

**Comment by Urigo** [comment] 2017-06-26 10:49
@davideberlein care to try making a PR to the doc?  always the best PRs are from the ones who actually got confused by it

**Comment by davideberlein** [comment] 2017-06-26 11:20
@Urigo if you point me to the right `md` file I'll do that

**Comment by Urigo** [comment] 2017-06-26 11:23
@davideberlein sure!  https://github.com/apollographql/angular-docs/blob/master/source/queries.md#using-with-rxjs
(also on each of our doc pages there is a "Edit on Github" button at the bottom)

**Comment by davideberlein** [comment] 2017-06-26 11:59
done see https://github.com/apollographql/angular-docs/pull/59
