### ISSUE TITLE
`mutate` return type is always `any`

### ISSUE THREAD

**Issue by fxck** [apollographql/apollo-angular#465] opened 2018-01-21 08:38 UTC
If I do this

```typescript
this._apollo
      .query<{ getCats: CatEntityBase[]; }>({
        query: gql`{ getCats { uid, name } }`
      })
      .pipe(map((resp) => resp.data.getCats));
```

`resp` has the correct type, but if I do the same with `mutate`, 

```typescript
    return this._apollo
      .mutate<{ addCat: CatEntityBase; }>({
        mutation: gql`mutation addCat($uid: String!, $name: String) {
          addCat(uid: $uid, name: $name) {
            uid, name
          }
        }`,
        variables: { name, uid }
      })
      .pipe(map((resp) => resp.data.addCat));
```

`resp` is `any`, despite both methods having the same signature?

```
    query<T, V = R>(options: WatchQueryOptions & TypedVariables<V>): Observable<ApolloQueryResult<T>>;
    mutate<T, V = R>(options: MutationOptions & TypedVariables<V>): Observable<FetchResult<T>>;
```

**Comment by beagleknight** [comment] 2018-01-22 08:44
@fxck I am having the same issue right now :)

The problem is `FetchResult` doesn't use `T` for the result:

```typescript
export declare type FetchResult<C = Record<string, any>, E = Record<string, any>> = ExecutionResult & {
    extensions?: E;
    context?: C;
};
```

The `C` here is the previous `T` and it used to type the context. I think this is an error but I am not 100% sure.

**Comment by fxck** [comment] 2018-01-23 05:57
What do you think @kamilkisiela ?

**Comment by kamilkisiela** [comment] 2018-01-23 09:29
Yep, at least three things that should be changed:

Apollo service in this lib: https://github.com/apollographql/apollo-angular/blob/502b57aa19d15be8719d77c284272299831f68a4/packages/apollo-angular/src/Apollo.ts#L37

QueryManager in apollo-client:
https://github.com/apollographql/apollo-client/blob/b1e389560d32c01bcb680514fc7f5dd8d94f2646/packages/apollo-client/src/core/QueryManager.ts#L127

And ApolloClient class:
https://github.com/apollographql/apollo-client/blob/b1e389560d32c01bcb680514fc7f5dd8d94f2646/packages/apollo-client/src/ApolloClient.ts#L253


I don't think `graphql` library supports a generic type to specify `data` structure so apollo-client itself would have to handle it, `ApolloMutationResult<T> & FetchResult` or similar.

**Comment by fxck** [comment] 2018-01-23 10:05
Hm, so that means PRs and releases on both repositories. Hoped it would be something we could fix quickly. :/

**Comment by kamilkisiela** [comment] 2018-01-23 10:30
I could help if anyone is interested in fixing it

**Comment by kamilkisiela** [comment] 2018-01-27 20:01
Closing since it's a duplication of apollographql/apollo-client#2795

**Closed by kamilkisiela** 2018-01-27 20:01 UTC
Labels: help wanted
